### ISSUE TITLE
Add default `hidden` styles to show-when elements

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/only-show#3]
Browsers consider the `hidden` attribute to be a presentational hint - applied without specificity before any document styles. The problem with that is setting `only-show { display: block }` now overrides the hidden attribute. In most cases, we just want to change the display _when the element is visible_, and we're not actually trying to override that visibility. I think it would make sense to add a shadow-attached stylesheet to these elements:

```css
:host([hidden]) { display:none !important; }
```

If we feel like there are use-cases where a document might want to override that, we could do one of these:

```css
:host([hidden]) { display: var(--override-hidden-display, none) !important; }
:host([hidden]:not([page-hide])) { display:none !important; }
```
